# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-Filter-GenericChunk
version:      0.07
version_from: GenericChunk.pm
installdirs:  site
requires:
    XML::LibXML:                   1.4
    XML::SAX::Base:                1.03

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
